---

# Pipeline container image pull policy,
# normally 'always'
pipeline_image_pull_policy: Always

# The namespace to launch pipelines from,
# e.g. the Squonk namespace.
pipeline_namespace: squonk
# A valid service account in the namespace
pipeline_namespace_service_account: squonk
# A preferred node purpose on which to run the Job
pipeline_node_purpose: application

# General variables -----------------------------------------------------------

# General timeout, generally used within the k8s module,
# for wait duration
wait_timeout: 600

# Kubernetes credentials ------------------------------------------------------

# We don't use the Kubernetes credentials directly,
# but we load them into variables here from their
# expected environment variables so that we can assert they've been set.
#
# If we're using OpenShift credentials these environment variables
# will not be set and we will therefore rely on them being set
# from the 'login.yaml' play.

k8s_auth_host: "{{ lookup('env', 'K8S_AUTH_HOST') }}"
k8s_auth_api_key: "{{ lookup('env', 'K8S_AUTH_API_KEY') }}"
