---

# A valid service account in the namespace
pipeline_namespace_service_account: squonk

# General variables -----------------------------------------------------------

# General timeout, generally used within the k8s module,
# for wait duration
wait_timeout: 600

# Kubernetes credentials ------------------------------------------------------

# We don't use the Kubernetes credentials directly,
# but we load them into variables here from their
# expected environment variables so that we can assert they've been set.

k8s_auth_host: "{{ lookup('env', 'K8S_AUTH_HOST') }}"
k8s_auth_api_key: "{{ lookup('env', 'K8S_AUTH_API_KEY') }}"
