---

- name: Create namespace '{{ ccd_namespace }}'
  k8s:
    definition: "{{ lookup('template', '{{ item }}.yaml.j2') }}"
    wait: yes
  loop:
  - namespace
  - serviceaccount
  - role-psp-unrestricted
  - rolebinding-ccd-sa

# Check and create database secrets

- name: Check database secrets
  k8s_info:
    kind: Secret
    api_version: v1
    namespace: "{{ ccd_namespace }}"
    name: database
  register: s_result

- name: Set database secret facts
  set_fact:
    ccd_database_user_password_fact: "{{ ccd_database_user_password }}"
    ccd_database_chemcentral_user_password_fact: "{{ ccd_database_chemcentral_user_password }}"
  when: s_result.resources|length == 0

- name: Set database secret facts (pre-deployed secrets)
  set_fact:
    ccd_database_user_password_fact: "{{ s_result.resources[0].data.user_password|b64decode }}"
    ccd_database_chemcentral_user_password_fact: "{{ s_result.resources[0].data.chemcentral_user_password|b64decode }}"
  when: s_result.resources|length == 1

- name: Write database secrets
  k8s:
    definition: "{{ lookup('template', 'secret.yaml.j2') }}"
    wait: yes
  when: s_result.resources|length == 0

# The database volume (and storage class checks)

- name: Get {{ ccd_database_volume_storageclass }} StorageClass
  k8s_info:
    kind: StorageClass
    name: "{{ ccd_database_volume_storageclass }}"
  register: sc_result
  when: ccd_database_volume_storageclass != " "

- name: Assert {{ ccd_database_volume_storageclass }} StorageClass
  assert:
    that: sc_result.resources|length == 1
    fail_msg: The {{ ccd_database_volume_storageclass }} StorageClass must be available on the cluster
  when: ccd_database_volume_storageclass != " "

- name: Create volume claims
  k8s:
    definition: "{{ lookup('template', '{{ item }}.yaml.j2') }}"
    wait: yes
    wait_timeout: "{{ wait_timeout }}"
  loop:
  - pvc-db
  - pvc-loader

# Best practice ... wait for the PVC to bind.
# e.g. wait until resources[0].status.phase == Bound (initially Pending)

- name: Wait for volume claims to bind
  k8s_info:
    kind: PersistentVolumeClaim
    name: "{{ item }}"
    namespace: "{{ ccd_namespace }}"
  register: database_result
  until: >-
    database_result.resources|length > 0
    and database_result.resources[0].status is defined
    and database_result.resources[0].status.phase == 'Bound'
  delay: 5
  retries: "{{ (bind_timeout|int / 5)|int }}"
  loop:
  - database
  - loader
  when: bind_timeout|int > 0

# Deploy the ChemCentral database

- name: Create database
  k8s:
    definition: "{{ lookup('template', '{{ item }}.yaml.j2') }}"
    wait: yes
  loop:
  - configmap-db-init
  - statefulset
  - service

- name: Wait for database to become Ready
  k8s_info:
    kind: Pod
    name: database-0
    namespace: "{{ ccd_namespace }}"
  register: database_result
  until: >-
    database_result.resources|length == 1
    and database_result.resources[0].status is defined
    and database_result.resources[0].status.containerStatuses is defined
    and database_result.resources[0].status.containerStatuses|length == 1
    and database_result.resources[0].status.containerStatuses[0].ready
  delay: 15
  retries: "{{ (wait_timeout|int / 15)|int }}"
