---

- include_tasks: prep.yaml

# If it looks like we're deploying to OpenShift
# we need to use the k8s authentication module to login
# and obtain an API key.
- include_tasks: login.yaml
  when: okd_master_hostname is defined

# A kubernetes (or OpenShift) host and an API key must be set.
# We will either have authenticated against an OpenShift server
# or the AWX kubernetes credentials will have injected suitable
# values for the K8S_AUTH_HOST and K8S_AUTH_API_KEY environment variables.
# Either way the ansible variables 'k8s_auth_host' and
# 'k8s_auth_api_key' will have been set.
- name: Assert authentication
  assert:
    that:
    - k8s_auth_host|length > 0
    - k8s_auth_api_key|length > 0

# Run the loader....
# but first check the sanity of variables
# before checking that the namespace exists.

- name: Check control variables
  assert:
    that:
    - ccd_loader_table_name|string|length > 0
    - ccd_loader_table_name|string != 'SetMe'
    - ccd_loader_class|string|length > 0
    - ccd_loader_class|string != 'SetMe'
    - ccd_loader_file != 'SetMe' or ccd_loader_path != 'SetMe'

- name: Check multi-file loader control variables
  assert:
    that:
    - ccd_loader_pattern|string|length > 0
    - ccd_loader_pattern|string != SetMe
  when: ccd_loader_path != 'SetMe'

- block:

  - name: Get expected namespace
    k8s_info:
      kind: Namespace
      name: "{{ ccd_namespace }}"
    register: namespace_info

  - name: Assert namespace exists
    assert:
      that: namespace_info.resources|length > 0
      fail_msg: Namespace '{{ ccd_namespace }}' does not exist

  - name: Remove existing loader
    k8s:
      state: absent
      definition: "{{ lookup('template', 'job-loader.yaml.j2') }}"
      wait: yes
      wait_timeout: "{{ wait_timeout }}"

  - name: Run loader
    k8s:
      definition: "{{ lookup('template', 'job-loader.yaml.j2') }}"

  module_defaults:
    group/k8s:
      host: "{{ k8s_auth_host }}"
      api_key: "{{ k8s_auth_api_key }}"

# If it looks like we're deploying to OpenShift
# we now need to logout...
- include_tasks: logout.yaml
  when: okd_master_hostname is defined
