---

# Do we expect to use the Kubernetes cert-manager?
sq_use_cert_manager: yes
# The namespace service account
sq_namespace_service_account: squonk
# The preferred node purpose for our objects
sq_node_purpose: application

sq_keycloak_realm: im
sq_keycloak_je_client_id: sje

# Size and class of the Squonk working directory.
# The class is 'blank', which implies the default class.
sq_workdir_volume_size_g: 50
sq_workdir_volume_storageclass: " "

# If using the cert-manager...
# the Cert-Manager issuers for external ingress
# (one of 'staging' or 'production')
sq_je_cert_issuer: staging
sq_portal_cert_issuer: staging

# The Squonk CellExecutor Pod environment
sq_pod_env: ''

sq_pod_log_history: 100
sq_nextflow_image: informaticsmatters/nextflow:19.10.0

sq_cell_cpu_request: 500m
sq_cell_mem_request: 400Mi
sq_cell_cpu_limit: 4000m
sq_cell_mem_limit: 8Gi
sq_cell_java_tool_options: -Xmx7800m

sq_chem_cpu_request: 500m
sq_chem_mem_request: 400Mi
sq_chem_cpu_limit: 4000m
sq_chem_mem_limit: 8Gi
sq_chem_java_tool_options: -Xmx7800m

sq_core_cpu_request: 500m
sq_core_mem_request: 3500Mi
sq_core_cpu_limit: 2000m
sq_core_mem_limit: 8Gi
sq_core_java_tool_options: -Xmx7800m

sq_je_cpu_request: 500m
sq_je_mem_request: 2200Mi
sq_je_cpu_limit: 4000m
sq_je_mem_limit: 8Gi
sq_je_java_tool_options: -Xmx7800m

sq_portal_cpu_request: 500m
sq_portal_mem_request: 1Gi
sq_portal_cpu_limit: 2000m
sq_portal_mem_limit: 8Gi

# RabbitMQ configuration ------------------------------------------------------

# The RabbitMQ image tag.
# We deploy using hte image tag '<version>-management-alpine'.
sq_rabbitmq_version: 3.6.16

sq_rabbitmq_cpu_request: 250m
sq_rabbitmq_mem_request: 1024Mi
sq_rabbitmq_cpu_limit: 1000m
sq_rabbitmq_mem_limit: 1024Mi

# RabbitMQ passwords and cookies
# Set but you cannot change this once RabbitMQ had been deployed
sq_rabbitmq_default_user_password: "{{ lookup('password', '/dev/null length=10 chars=ascii_letters,digits') }}"
# Set but you cannot change this once RabbitMQ had been deployed
sq_rabbitmq_erlang_cookie: "{{ lookup('password', '/dev/null length=96 chars=ascii_letters,digits') }}"

# General variables -----------------------------------------------------------

# General timeout, generally used within the k8s module,
# for wait duration
wait_timeout: 600
# Volume binding timeout (seconds)
bind_timeout: 120

# Valid certificate issuers
# For the kubernetes certificate manager
cert_issuers:
- staging
- production

# Kubernetes credentials ------------------------------------------------------

# We don't use the Kubernetes credentials directly,
# but we load them into variables here from their
# expected environment variables so that we can assert they've been set.
#
# If we're using OpenShift credentials these environment variables
# will not be set and we will therefore rely on them being set
# from the 'login.yaml' play.

k8s_auth_host: "{{ lookup('env', 'K8S_AUTH_HOST') }}"
k8s_auth_api_key: "{{ lookup('env', 'K8S_AUTH_API_KEY') }}"
