---

# The preferred node purpose for our objects
sq_node_purpose: application

# Size and class of the Squonk working directory.
# The class is 'blank', which implies the default class.
sq_workdir_volume_size_g: 50
sq_workdir_volume_storageclass: " "

# If using the cert-manager...
# the Cert-Manager issuers for external ingress
# (one of 'staging' or 'production')
sq_je_cert_issuer: production
sq_portal_cert_issuer: production
sq_website_cert_issuer: production

# The Squonk CellExecutor Pod environment
sq_pod_env: ''

sq_pod_log_history: 100
sq_nextflow_image: informaticsmatters/nextflow:19.10.0

sq_cell_cpu_request: 500m
sq_cell_mem_request: 400Mi
sq_cell_cpu_limit: 4000m
sq_cell_mem_limit: 8Gi
sq_cell_java_tool_options: -Xmx7800m

sq_chem_cpu_request: 500m
sq_chem_mem_request: 400Mi
sq_chem_cpu_limit: 4000m
sq_chem_mem_limit: 8Gi
sq_chem_java_tool_options: -Xmx7800m

sq_css_cpu_request: 500m
sq_css_mem_request: 1200Mi
sq_css_cpu_limit: 2
sq_css_mem_limit: 8Gi
sq_css_java_tool_options: -Xmx7800m

sq_core_cpu_request: 500m
sq_core_mem_request: 3500Mi
sq_core_cpu_limit: 2000m
sq_core_mem_limit: 8Gi
sq_core_java_tool_options: -Xmx7800m

sq_je_cpu_request: 500m
sq_je_mem_request: 2200Mi
sq_je_cpu_limit: 4000m
sq_je_mem_limit: 8Gi
sq_je_java_tool_options: -Xmx7800m

sq_portal_cpu_request: 500m
sq_portal_mem_request: 1Gi
sq_portal_cpu_limit: 2000m
sq_portal_mem_limit: 8Gi

# Squonk images (tags are defined in defaults)
sq_flyway_image: squonk/flyway

# RabbitMQ configuration ------------------------------------------------------

# The RabbitMQ image tag.
# We deploy using hte image tag '<version>-management-alpine'.
sq_rabbitmq_version: 3.6.16

sq_rabbitmq_cpu_request: 250m
sq_rabbitmq_mem_request: 1024Mi
sq_rabbitmq_cpu_limit: 1000m
sq_rabbitmq_mem_limit: 1024Mi

# RabbitMQ passwords and cookies
# Set but you cannot change this once RabbitMQ had been deployed
sq_rabbitmq_default_user_password: "{{ lookup('password', '/dev/null length=10 chars=ascii_letters,digits') }}"
# Set but you cannot change this once RabbitMQ had been deployed
sq_rabbitmq_erlang_cookie: "{{ lookup('password', '/dev/null length=96 chars=ascii_letters,digits') }}"

# Variables for the Keycloak realm manager
# Set or leave for automatic assignment
sq_keycloak_realm_manager: manager
sq_keycloak_realm_manager_password: "{{ lookup('password', '/dev/null length=12 chars=ascii_letters,digits') }}"

# General variables -----------------------------------------------------------

# General timeout, generally used within the k8s module,
# for wait duration
wait_timeout: 600
# Volume binding timeout (seconds)
bind_timeout: 120

# Valid certificate issuers
# For the kubernetes certificate manager
cert_issuers:
- staging
- production

# Keycloak credentials --------------------------------------------------------

# Either leave unset (where credentials will be obtained from the
# infrastructure namespace on the cluster) or set them, usually when
# using a remote keycloak server.
#
# Normally these are left unset or they're provided by AWX custom credentials.

keycloak_server_url: ''
keycloak_admin: ''
keycloak_admin_password: ''
