---

# The application namespace
ccs_namespace: chemcentral-search
# The preferred node purpose for our objects
ccs_node_purpose: application

# Search resource limits
ccs_cpu_limit: 2
ccs_cpu_request: 250m
ccs_mem_limit: 8Gi
ccs_mem_request: 1200Mi

# Search image details
ccs_image_registry: docker.io
ccs_image: squonk/chemcentral-search
ccs_image_tag: 0.3.11

# A value used for the Java application's JAVA_TOOL_OPTIONS
# environment variable. The values are used by the container's
# underlying JVM. Use of -Xmx for example is a convenient
# way of setting the maximum JVM heap and should lie somewhere
# between the MEM_REQUEST and MEM_LIMIT (certainly less than the limit
# to allow for some 'headroom' for allocations other than from the JVM).
ccs_java_tool_options: -Xmx7800m

# Database image details
ccs_database_image_registry: docker.io
ccs_database_image: informaticsmatters/rdkit_cartridge
ccs_database_image_tag: Release_2017_09_2

# Database resource limits
ccs_database_cpu_limit: 4
ccs_database_cpu_request: 100m
ccs_database_mem_limit: 2Gi
ccs_database_mem_request: 100Mi

# Database passwords,
# randomly assigned unless defined.
ccs_database_user_password: "{{ lookup('password', '/dev/null length=12 chars=ascii_letters') }}"
ccs_database_chemcentral_user_password: "{{ lookup('password', '/dev/null length=14 chars=ascii_letters') }}"

# General variables -----------------------------------------------------------

# General timeout, generally used within the k8s module,
# for wait duration
wait_timeout: 600
# Volume binding timeout (seconds)
bind_timeout: 120

# -----------------------------------------------------------------------------
#
# The search container belongs to Squonk deployment.
# The database is 'central', i.e. independent of squonk and in its own namespace.
# So we can have N Squonks and (typically) 1 db.
# The database Squonk uses for the search is driven by environment variables
# declared in the ChemcentralConfig class ...
#
# "CHEMCENTRAL_HOST"
# "CHEMCENTRAL_PORT"
# "CHEMCENTRAL_DB"
# "CHEMCENTRAL_USER"
# "CHEMCENTRAL_PASSWORD"
#
# Q. And it sounds like a new set of credentials in AWX?
#    That are injected into the Squonk AWX play (and the search DB deployment play)?
#    Discuss the real need for DB, USER, PASSWORD with Tim -i.e. are they just 'well known'?
#
# Q  Another thought ... is the chemcentral database a completely separate repo?
#    i.e. an "ansible-chemcentral-database" repo and role or is to so tightly
#    coupled with Squonk it belongs in Squonk?
