---

- name: Pre-flight checks ({{ pipeline_name }})
  assert:
    that:
    - pipeline_name|length > 0
    - pipeline_name != 'SetMe'
    - pipeline_repository|length > 0
    - pipeline_repository != 'SetMe'

- name: Get pull secret
  k8s_info:
    kind: Secret
    namespace: "{{ pipeline_namespace }}"
    name: "{{ pipeline_pull_secret }}"
  register: result
  when: pipeline_pull_secret|length > 0

- name: Check pull secret
  assert:
    that: result.resources|length == 1
    fail_msg: The pull secret does not exist ({{ pipeline_pull_secret }})
  when: pipeline_pull_secret|length > 0

- name: Remove any existing pipeline Job ({{ pipeline_name }})
  k8s:
    state: absent
    definition: "{{ lookup('template', 'job-pipeline-poster.yaml.j2') }}"
    wait: yes

# Delete the Pods left behind that are Completed ('Succeeded').
# Kubernetes *DOES NOT* remove these Job-based Pods automatically
# (see https://kubernetes.io/docs/concepts/workloads/controllers/job/).
# Instead completed Jobs need to be removed manually by the user.
# The logic that follows list all Jobs (Pods)
# that have Succeeded and then deletes them.

- name: Get Succeeded RDkit Pipleines Pods
  k8s_info:
    kind: Pod
    namespace: "{{ pipeline_namespace }}"
    label_selectors:
    - name=rdkit-pipelines
    field_selectors:
    - status.phase=Succeeded
  register: pods_result

- name: Delete Succeeded RDkit Pipleines Pods
  k8s:
    kind: Pod
    namespace: "{{ pipeline_namespace }}"
    name: "{{ item.metadata.name }}"
    state: absent
  loop: "{{ pods_result.resources }}"
  when: pods_result.resources|length > 0

# All clean - start a new Job

- name: Launch new pipeline Job ({{ pipeline_name }})
  k8s:
    definition: "{{ lookup('template', 'job-pipeline-poster.yaml.j2') }}"
    wait: yes
    wait_timeout: "{{ wait_timeout }}"

- name: Wait for pipeline ({{ pipeline_name }})
  k8s_info:
    kind: Job
    namespace: "{{ pipeline_namespace }}"
    name: "{{ pipeline_name }}"
  register: result
  until: >-
    result.resources[0].status.completionTime is defined
    or result.resources[0].status.failed is defined
  delay: 15
  retries: "{{ (wait_timeout|int / 15)|int }}"

- name: Display Job status ({{ pipeline_name }})
  debug:
    var: result.resources[0].status

- name: Assert pipeline success ({{ pipeline_name }})
  assert:
    that:
    - result.resources[0].status.succeeded is defined
    - result.resources[0].status.succeeded == 1
    - result.resources[0].status.failed is not defined
