---

# The application namespace
ccd_namespace: chemcentral-database

# Database image details
ccd_database_image_registry: docker.io
ccd_database_image: informaticsmatters/rdkit-cartridge-debian
ccd_database_image_tag: Release_2020_03_4
ccd_database_loader_image_tag: 0.3.11

# Database resource limits
ccd_database_cpu_limit: 4
ccd_database_cpu_request: 100m
ccd_database_mem_limit: 4Gi
ccd_database_mem_request: 1Gi

# Database passwords,
# randomly assigned unless defined.
ccd_database_user_password: "{{ lookup('password', '/dev/null length=12 chars=ascii_letters') }}"
ccd_database_chemcentral_user_password: "{{ lookup('password', '/dev/null length=14 chars=ascii_letters') }}"

# Loader variables ------------------------------------------------------------

ccd_loader_cpu_limit: 2
ccd_loader_cpu_request: 250m
ccd_loader_mem_limit: 2Gi
ccd_loader_mem_request: 100Mi

# General variables -----------------------------------------------------------

# General timeout, generally used within the k8s module,
# for wait duration
wait_timeout: 600
# Volume binding timeout (seconds)
# Set to 0 to avoid waiting
bind_timeout: 120
