---

# Deploy (or un-deploy)?
# One of 'present' or 'absent'.
sq_state: present
sq_website_state: present

# A the name of the parameter vault for the deployment.
# Used to load deployment-specific variables
# from the file '{{ sq_name }}-parameters.vault'
# The name it typically different for each deployment.
sq_parameter_vault: im-main

# The application namespace
sq_namespace: squonk
# The infrastructure namespace
# The database is expected here,
# as the host 'database.{{ sq_infra_namespace }}.svc'
sq_infra_namespace: im-infra
# The name of the database (and a user that'll own it)
# that'll be created in the infrastructure's PostgreSQL server
sq_infra_database: squonk
sq_infra_database_owner: squonk
# The squonk Keycloak realm
# by default he name of the namespace
sq_keycloak_realm: squonk
# Delete the realm on removal?
sq_delete_keycloak_realm_on_removal: yes

# A list of Realm users to deploy.
# This utilises the informaticsmatters.infrastructure_user Role
# so refer to that role for documentation.
sq_day1_users: []

# Hostname definitions (ingress)
# There is essentially one hostname for Squonk,
# but a number of paths. Typically we deploy
# a deployment-specific website, the portal (Squonk notebook),
# and the JobExecutor, available at the following URLs:-
#
# website: https://{{ sq_hostname }}
# website: https://{{ sq_hostname }}/portal
# website: https://{{ sq_hostname }}/jobexecutor
sq_hostname: ''

# Keycloak material...
sq_portal_keycloak_client_id: squonk-notebook
sq_portal_keycloak_client_secret: ''
sq_je_keycloak_client_id: squonk-jobexecutor

# Delete the Squonk database when Squonk is removed?
sq_delete_db_on_removal: yes
# Set a database password otherwise it'll be randomly generated.
sq_db_password: SetMe

# Squonk container image registries and tags
sq_image_registry: docker.io
sq_image_tag: '0.5.8'
sq_portal_registry: docker.io
sq_portal_image_tag: '0.4.1'
sq_website_registry: registry.gitlab.com
sq_website_image: informaticsmatters/squonk-website
sq_website_image_tag: stable

# Pipeline (Pod) pull policy
sq_pod_image_pull_policy: IfNotPresent

# Size and class of the Squonk working directory.
# The class is 'blank', which implies the default class.
sq_workdir_volume_size_g: 1
sq_workdir_volume_storageclass: " "

# Debug modes (passed to the cell-executor)
sq_debug_mode: 0
sq_pod_debug_mode: 0
# The Pod CPU resource (and limit) for cell and job-executor Jobs.
# Passed to squonk containers via the resources/cpu/limit and request.
sq_pod_cpu_resource: '1'
# Worker pod affinity value.
# Cells are required to run on nodes with our affinity label
sq_pod_node_affinity_value: worker
# The Squonk Pod Nextflow Queue size
# Internal default is 100.
sq_nf_queue_size: 20

# Container credentials used to create secrets
# in order to pull images from private registries.
#
# A list of 'name' and 'secret' values that are used to create secrets
# in the project namespace.
#
# Typically: -
#
#   sq_pull_secrets:
#   - name: abc-gitlab
#     secret: eyJodHRwczovL2luZGV4L ... J0QUl6RTIifX0=
#
# See the project README for instructions
# on creating the 'secret' value.
sq_pull_secrets: []

# ChemAxon License File.
# This is mapped into the ChemServices container
# using a config map. The license is empty by default.
#
# If you want to use ChemAxon services you must supply a license
# in this variable.
sq_chemaxon_license: >-
  <?xml version="1.0" encoding="UTF-8" standalone="no"?>
  <ChemAxon>
  </ChemAxon>

# A pull-secret for public images pulled from DockerHub.
# If set this is the base-64 string that can be used as the value
# in our Kubernetes Secret as the .dockerconfigjson value.
# If set it is applied to the ServiceAccount in the namespace
# and applied to Pods that use that namespace.
sq_dockerhub_pullsecret: ''

# ChemCentral Search ----------------------------------------------------------

# Deploy (or undeploy) ChemCentral Search?
sq_ccs_state: present

# ChemCentral Search Database namespace.
# Assume the default location in the cluster.
sq_ccs_database_namespace: chemcentral-database
