---

# Deploy (or un-deploy)?
# One of 'present' or 'absent'.
sq_state: present

# A the name of the parameter vault for the deployment.
# Used to load deployment-specific variables
# from the file '{{ sq_name }}-parameters.vault'
# The name it typically different for each deployment.
sq_parameter_vault: im-main

# The application namespace
sq_namespace: squonk
# The infrastructure namespace
# The database is expected here,
# as the host 'database.{{ sq_infra_namespace }}.svc'
sq_infra_namespace: im-infra
# The name of the database (and a user that'll own it)
# that'll be created in the infrastructure's PostgreSQL server
sq_infra_database: squonk
sq_infra_database_owner: squonk
# The squonk Keycloak realm
# by default he name of the namespace
sq_keycloak_realm: squonk
# Delete the realm on removal?
sq_delete_keycloak_realm_on_removal: no

# A list of Realm users to deploy.
# This utilises the informaticsmatters.infrastructure_user Role
# so refer to that role for documentation.
sq_day1_users: []

# The hostname that routes to the portal
sq_portal_hostname: ''
sq_portal_logout_redirect_to: ''
sq_portal_keycloak_client_id: squonk-notebook
sq_portal_keycloak_client_secret: ''

# The hostname that routes to the JobExecutor
sq_je_hostname: ''
sq_je_keycloak_client_id: squonk-jobexecutor

# Delete the Squonk database when Squonk is removed?
sq_delete_db_on_removal: yes
# Set a database password otherwise it'll be randomly generated.
sq_db_password: SetMe

# Squonk container image tags
sq_image_tag: '0.3.9'
sq_portal_image_tag: '0.3.6'

# Container credentials used to create secrets
# in order to pull images from private registries.
#
# A list of 'name' and 'secret' values that are used to create secrets
# in the project namespace.
#
# Typically: -
#
#   sq_pull_secrets:
#   - name: abc-gitlab
#     secret: eyJodHRwczovL2luZGV4L ... J0QUl6RTIifX0=
#
# See the project README for instructions
# on creating the 'secret' value.
sq_pull_secrets: []
