---

# Deploy (or un-deploy)?
# One of 'present' or 'absent'.
sq_state: present

# The application namespace
sq_namespace: squonk
# The infrastructure namespace
# The database is expected here,
# as the host 'database.{{ sq_infra_namespace }}.svc'
sq_infra_namespace: im-infra

# The hostname that routes to the portal
sq_portal_hostname: ''
sq_portal_logout_redirect_to: ''
sq_portal_keycloak_client_id: squonk-notebook
sq_portal_keycloak_client_secret: ''

# The hostname that routes to the JobExecutor
sq_je_hostname: ''
sq_je_keycloak_client_id: squonk-jobexecutor

# Delete the Squonk database when Squonk is removed?
sq_delete_db_on_removal: yes
# Set a database password otherwise it'll be randomly generated.
sq_db_password: SetMe

# The hostname of the Keycloak server
# i.e. example.com, 'https://' is assumed
sq_keycloak_hostname: SetMe
# Keycloak admin user credentials.
# If not defined the playbook will assume that
# secrets exist in the namespace declared in 'sq_infra_namespace'
sq_keycloak_admin_user: ''
sq_keycloak_admin_user_password: ''

# Squonk container image tags
sq_core_image_tag: '0.3.5'
sq_cell_image_tag: '0.3.5'
sq_chem_image_tag: '0.3.5'
sq_je_image_tag: '0.3.5'
sq_flyway_image_tag: '0.3.5'
sq_portal_image_tag: 'latest'
