---

# Create the keycloak clients
# We have a client for the Portal (the web application)
# and one for the JobExecutor...


# Now that we have a namespace
# we must create a database for use by Squonk.
# This is handled by our infrastructure-config Role.
#
# Assuming database credentials do no already exist.

- name: Get database secrets
  k8s_facts:
    kind: Secret
    name: database-secrets-squonk
    namespace: "{{ sq_namespace }}"
  register: secret_result

- name: Create infrastructure database for Squonk
  include_role:
    name: informaticsmatters.infrastructure_config
  vars:
    ic_action: create
    ic_infra_namespace: "{{ sq_infra_namespace }}"
    ic_db: squonk
    ic_db_user_namespace: "{{ sq_namespace }}"
    ic_db_user: squonk
    ic_db_user_password: "{{ sq_db_password }}"
  when: secret_result.resources|length == 0

- import_tasks: infra-db-migration.yaml
