---

# We must create a database for use by Squonk.
# This is handled by our infrastructure-data Role.
#
# Assuming database credentials do not already exist.

- name: Get database secrets
  k8s_info:
    kind: Secret
    name: database-secrets-{{ sq_infra_database }}
    namespace: "{{ sq_namespace }}"
  register: secret_result

- block:

  - name: Assert variables
    assert:
      that:
      - sq_db_password|length > 0
      - sq_db_password != 'SetMe'

  - name: Create infrastructure database for Squonk
    include_role:
      name: informaticsmatters.infrastructure_data
    vars:
      id_action: create
      id_infra_namespace: "{{ sq_infra_namespace }}"
      id_db: "{{ sq_infra_database }}"
      id_db_user_namespace: "{{ sq_namespace }}"
      id_db_user_namespace_sa: "squonk"
      id_db_user: "{{ sq_infra_database_owner }}"
      id_db_user_password: "{{ sq_db_password }}"

  when: secret_result.resources|length == 0

- import_tasks: infra-db-migration.yaml

# Create Keycloak Realm (and Roles)

- import_tasks: get-keycloak-credentials.yaml
- import_tasks: get-keycloak-realm-manager-credentials.yaml

- name: Create Keycloak Realm ({{ sq_keycloak_realm }})
  include_role:
    name: informaticsmatters.infrastructure_user
  vars:
    iu_action: create
    iu_type: realm
    iu_hostname: "{{ sq_keycloak_hostname_fact }}"
    iu_namespace: "{{ sq_namespace }}"
    iu_realm: "{{ sq_keycloak_realm }}"
    iu_realm_manager: "{{ sq_keycloak_realm_manager_fact }}"
    iu_realm_manager_password: "{{ sq_keycloak_realm_manager_password_fact }}"
    iu_admin_user: "{{ sq_keycloak_admin_user_fact }}"
    iu_admin_password: "{{ sq_keycloak_admin_user_password_fact }}"

- name: Create Keycloak Realm Roles
  include_role:
    name: informaticsmatters.infrastructure_user
  vars:
    iu_action: create
    iu_type: role
    iu_hostname: "{{ sq_keycloak_hostname_fact }}"
    iu_realm: "{{ sq_keycloak_realm }}"
    iu_realm_manager: "{{ sq_keycloak_realm_manager_fact }}"
    iu_realm_manager_password: "{{ sq_keycloak_realm_manager_password_fact }}"
    iu_roles:
    - name: standard-user
      default: yes
    - name: fragnet-search

# Create the keycloak clients
# We have a client for the Portal (the web application)
# and one for the JobExecutor...

- name: Add Keycloak JobExecutor client
  keycloak_client:
    auth_client_id: admin-cli
    auth_keycloak_url: "{{ sq_keycloak_url_fact }}"
    auth_realm: master
    auth_username: "{{ sq_keycloak_admin_user_fact }}"
    auth_password: "{{ sq_keycloak_admin_user_password_fact }}"
    realm: "{{ sq_keycloak_realm }}"
    client_id: "{{ sq_je_keycloak_client_id }}"
    name: Squonk JobExecutor
    protocol: openid-connect
    base_url: https://{{ sq_hostname }}
    admin_url: https://{{ sq_hostname }}
    redirect_uris:
    - https://{{ sq_hostname }}/jobexecutor/*
    - http://{{ sq_hostname }}/jobexecutor/*
    public_client: yes
    service_accounts_enabled: yes
    direct_access_grants_enabled: yes
    standard_flow_enabled: yes
    default_roles:
    - standard-user
  delegate_to: localhost
  when: sq_je_hostname|string|length > 0

- name: Add Keycloak Portal (Notebook) client
  keycloak_client:
    auth_client_id: admin-cli
    auth_keycloak_url: "{{ sq_keycloak_url_fact }}"
    auth_realm: master
    auth_username: "{{ sq_keycloak_admin_user_fact }}"
    auth_password: "{{ sq_keycloak_admin_user_password_fact }}"
    realm: "{{ sq_keycloak_realm }}"
    client_id: "{{ sq_portal_keycloak_client_id }}"
    name: Squonk Computational Notebook
    protocol: openid-connect
    base_url: https://{{ sq_hostname }}/portal
    admin_url: https://{{ sq_hostname }}/portal
    redirect_uris:
    - https://{{ sq_hostname }}/portal/*
    - http://{{ sq_hostname }}/portal/*
    client_authenticator_type: client-secret
    secret: "{{ sq_portal_keycloak_client_secret }}"
    public_client: no
    direct_access_grants_enabled: no
    standard_flow_enabled: yes
    default_roles:
    - standard-user
  delegate_to: localhost

# Create 'Day 1' Keycloak users

- name: Create Keycloak Realm 'Day 1' Squonk users
  include_role:
    name: informaticsmatters.infrastructure_user
  vars:
    iu_action: create
    iu_type: user
    iu_hostname: "{{ sq_keycloak_hostname_fact }}"
    iu_realm: "{{ sq_keycloak_realm }}"
    iu_realm_manager: "{{ sq_keycloak_realm_manager_fact }}"
    iu_realm_manager_password: "{{ sq_keycloak_realm_manager_password_fact }}"
    iu_users: "{{ sq_day1_users }}"
  when: sq_day1_users|length > 0
