---

- name: Creating namespace '{{ sq_namespace }}'
  k8s:
    definition: "{{ lookup('template', '{{ item }}.yaml.j2') }}"
    wait: yes
  loop:
  - namespace
  - serviceaccount
  - role-squonk-psp-unrestricted
  - rolebinding-squonk-sa

- name: Relax {{ sq_namespace }} 'default' service account (for cert-manager)
  k8s:
    definition: "{{ lookup('template', 'rolebinding-default-sa.yaml.j2') }}"
    wait: yes
  when: sq_use_cert_manager|bool

- name: Create 'workdir' volume claim
  k8s:
    definition: "{{ lookup('template', 'pvc-workdir.yaml.j2') }}"
    wait: yes
    wait_timeout: "{{ wait_timeout }}"

# Best practice ... wait for the PVC to bind.
# e.g. wait until resources[0].status.phase == Bound (initially Pending)

- name: Wait for 'workdir' volume claim to bind
  k8s_facts:
    kind: PersistentVolumeClaim
    name: workdir
    namespace: "{{ sq_namespace }}"
  register: workdir_result
  until: workdir_result.resources[0].status.phase == 'Bound'
  delay: 5
  retries: "{{ (bind_timeout|int / 5)|int }}"

- import_tasks: deploy-rabbitmq.yaml
