---

- name: Creating namespace '{{ sq_namespace }}'
  k8s:
    definition: "{{ lookup('template', '{{ item }}.yaml.j2') }}"
    wait: yes
  loop:
  - namespace
  - serviceaccount
  - role-squonk-psp-unrestricted
  - role-squonk-runner
  - rolebinding-squonk-psp-unrestricted-sa
  - rolebinding-squonk-runner-sa

- name: Relax {{ sq_namespace }} 'default' service account (for cert-manager)
  k8s:
    definition: "{{ lookup('template', 'rolebinding-default-sa.yaml.j2') }}"
    wait: yes
  when: sq_use_cert_manager|bool

- import_tasks: configure-infra.yaml

- import_tasks: deploy-rabbitmq.yaml
- import_tasks: deploy-squonk.yaml

# Display some useful information for the user...

- name: Display portal location
  debug:
    msg: >-
      The Squonk Portal should be available at
      https://{{ sq_portal_hostname }}/portal
