---

- name: Create 'workdir' volume claim
  k8s:
    definition: "{{ lookup('template', 'pvc-workdir.yaml.j2') }}"
    wait: yes
    wait_timeout: "{{ wait_timeout }}"

# Create secret objects for each image pull secret defined.
# These are typically used to pull pipeline container, SD-poster
# and website images from private registries.

- name: Create image pull secrets
  k8s:
    definition: "{{ lookup('template', 'secret-imagepull.yaml.j2') }}"
    wait: yes
  vars:
    pull_name: "{{ item.name }}"
    pull_secret: "{{ item.secret }}"
  with_items: "{{ sq_pull_secrets }}"

# Deploy the website and its service.
# The website is a Deployment in the Squonk namespace

- name: Deploy website
  k8s:
    definition: "{{ lookup('template', '{{ item }}.yaml.j2') }}"
    wait: yes
    wait_timeout: "{{ wait_timeout }}"
  loop:
  - deployment-website
  - service-website
  when:
  - sq_state|string == 'present'
  - sq_website_state|string == 'present'

# Deploy the main (backend) application images.
#
# As we 'wait' for individual containers we have to deploy
# in a dependent order - i.e. as chemservices depends on
# (i.e. has an init-container that waits) for coreservices
# then we must deploy coreservices first and we must also deploy
# services prior to their respective images.

- name: Deploy Squonk (BackEnd)
  k8s:
    definition: "{{ lookup('template', '{{ item }}.yaml.j2') }}"
    wait: yes
    wait_timeout: "{{ wait_timeout }}"
  loop:
  - secret-squonk
  - configmap-chemaxon-license
  - configmap-jobexecutor
  - service-cellexecutor
  - service-coreservices
  - service-jobexecutor
  - service-chemservices
  - deployment-cellexecutor
  - deployment-coreservices
  - deployment-jobexecutor
  - deployment-chemservices

# Deploy the Front-End (Portal)

- name: Deploy Squonk (Portal)
  k8s:
    definition: "{{ lookup('template', '{{ item }}.yaml.j2') }}"
    wait: yes
    wait_timeout: "{{ wait_timeout }}"
  loop:
  - service-portal
  - configmap-portal
  - deployment-portal

- name: Deploy Squonk ingress
  k8s:
    definition: "{{ lookup('template', 'ingress.yaml.j2') }}"
    wait: yes
