---

# Sets a number of facts: -
#
# - sq_keycloak_realm_manager_fact
# - sq_keycloak_realm_manager_password_fact

- name: Assert variables
  assert:
    that:
    - sq_infra_namespace|length > 0
    - sq_keycloak_realm|length > 0

- name: Get Keycloak Realm manager secrets (from '{{ sq_namespace }}' namespace)
  k8s_facts:
    kind: Secret
    name: realm-manager-{{ sq_keycloak_realm }}
    namespace: "{{ sq_namespace }}"
  register: krm_s_result

- block:

  # Extract Realm manager details from pre-deployed secrets...

  - name: Assert Keycloak realm manager secrets
    assert:
      that: krm_s_result.resources|length == 1

  - name: Set Keycloak realm manager facts (from secrets)
    set_fact:
      sq_keycloak_realm_manager_fact: "{{ krm_s_result.resources[0].data.username|b64decode }}"
      sq_keycloak_realm_manager_password_fact: "{{ krm_s_result.resources[0].data.password|b64decode }}"

  when: krm_s_result.resources|length > 0

- block:

  # No pre-deployed secrets
  # Set facts from variables.

  - name: Set Keycloak realm manager facts (from variables)
    set_fact:
      sq_keycloak_realm_manager_fact: "{{ sq_keycloak_realm_manager }}"
      sq_keycloak_realm_manager_password_fact: "{{ sq_keycloak_realm_manager_password }}"

  when: krm_s_result.resources|length == 0
