---

# Common playbook preparation.

# Expose ansible version
- debug:
    var: ansible_version.full

# Basic pre-playbook prerequisites.
# We need the openshift/kubernetes module amongst other things...

- name: Install prerequisite Python modules
  pip:
    name:
    - jmespath==0.9.4
    extra_args: --user

# Install required Ansible Galaxy modules

- name: Install Ansible Galaxy modules
  command: ansible-galaxy install -r requirements.yaml
  register: ag_result
  changed_when: "'downloading role' in ag_result.stdout"

# Kubernetes credentials ------------------------------------------------------

# We don't use the Kubernetes credentials directly,
# but we load them into variables here from their
# expected environment variables so that we can assert they've been set.

- name: Set initial authentication facts
  set_fact:
    k8s_auth_host: "{{ lookup('env', 'K8S_AUTH_HOST') }}"
    k8s_auth_api_key: "{{ lookup('env', 'K8S_AUTH_API_KEY') }}"
