---

- name: Get database secrets
  k8s_facts:
    kind: Secret
    name: database-secrets-squonk
    namespace: "{{ sq_namespace }}"
  register: secret_result
  when:
  - sq_delete_db_on_removal|bool

- name: Delete Squonk infrastructure database
  include_role:
    name: informaticsmatters.infrastructure_config
  vars:
    ic_action: delete
    ic_infra_namespace: "{{ sq_infra_namespace }}"
    ic_db: squonk
    ic_db_user_namespace: "{{ sq_namespace }}"
    ic_db_user: squonk
  when:
  - sq_delete_db_on_removal|bool
  - secret_result.resources|length == 1

- import_tasks: get-keycloak-credentials.yaml

- name: Remove Keycloak JobExecutor client
  local_action:
    module: keycloak_client
    auth_client_id: admin-cli
    auth_keycloak_url: https://{{ sq_keycloak_hostname }}/auth
    auth_realm: master
    auth_username: "{{ sq_keycloak_admin_user_fact }}"
    auth_password: "{{ sq_keycloak_admin_user_password_fact }}"
    realm: "{{ sq_keycloak_realm }}"
    client_id: "{{ sq_je_keycloak_client_id }}"
    state: absent

- name: Remove Keycloak Portal (Notebook) client
  local_action:
    module: keycloak_client
    auth_client_id: admin-cli
    auth_keycloak_url: https://{{ sq_keycloak_hostname }}/auth
    auth_realm: master
    auth_username: "{{ sq_keycloak_admin_user_fact }}"
    auth_password: "{{ sq_keycloak_admin_user_password_fact }}"
    realm: "{{ sq_keycloak_realm }}"
    client_id: "{{ sq_portal_keycloak_client_id }}"
    state: absent

- name: Delete namespace '{{ sq_namespace }}'
  k8s:
    state: absent
    definition: "{{ lookup('template', 'namespace.yaml.j2') }}"
    wait: yes
